=== angelicastoliarova/study/TASK9/test/by/tc/st/NewXMLSchema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.example.org/NewXMLSchema"
	xmlns:tns="http://www.example.org/NewXMLSchema" elementFormDefault="qualified">
	<element name="tests">
		<complexType>
			<sequence>
				<element name="test" type="tns:data" minOccurs="1"
					maxOccurs="10" />
			</sequence>
		</complexType>
	</element>

	<complexType name="data">
		<sequence>

			<element name="COMMAND_REGISTRATION" type="string" />
			<element name="COMMAND_AUTHORIZATION" type="string" />
			<element name="COMMAND_ADD_NEW_QUI" type="string" />
			<element name="COMMAND_FIND_QUI_BY_TEST" type="string" />
			<element name="COMMAND_FORM_NEW_TEST" type="string" />
			<element name="COMMAND_SHOW_ALL_TESTS" type="string" />
			<element name="IdQuetions" type="int" />
			<element name="Quetion" type="string" />
			<element name="IdSubject" type="int" />
			<element name="Subject" type="string" />
			<element name="IdTest" type="int" />
			<element name="IdCorrectAnswer" type="int" />
			<element name="CorrectAnswer" type="string" />
			<element name="LOGIN" type="string" />
			<element name="PASSWORD" type="string" />
			<element name="ROLE" type="string" />
			<element name="TESTANSWER" type="int" />


		</sequence>

		<attribute name="number" use="required">
		</attribute>

	</complexType>

</schema>

=== angelicastoliarova/study/TASK9/test/by/tc/st/NewXMLSchema.xml
<?xml version="1.0" encoding="UTF-8"?>
<tns:tests xmlns:tns="http://www.example.org/NewXMLSchema"
 xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://www.example.org/NewXMLSchema ../../../../by/NewXMLSchema.xsd ">
  <tns:test number="1">
    <tns:COMMAND_REGISTRATION>tns:Registration</tns:COMMAND_REGISTRATION>
    <tns:COMMAND_AUTHORIZATION>tns:Authentication</tns:COMMAND_AUTHORIZATION>
    <tns:COMMAND_ADD_NEW_QUI>tns:AddNewQui</tns:COMMAND_ADD_NEW_QUI>
    <tns:COMMAND_FIND_QUI_BY_TEST>tns:FindQuiByTest</tns:COMMAND_FIND_QUI_BY_TEST>
    <tns:COMMAND_FORM_NEW_TEST>tns:FormNewTest</tns:COMMAND_FORM_NEW_TEST>
    <tns:COMMAND_SHOW_ALL_TESTS>tns:ShowAllTests</tns:COMMAND_SHOW_ALL_TESTS>
    <tns:IdQuetions>16</tns:IdQuetions>
    <tns:Quetion>tns:what collections do you know</tns:Quetion>
    <tns:IdSubject>900</tns:IdSubject>
    <tns:Subject>tns:java</tns:Subject>
    <tns:IdTest>8</tns:IdTest>
    <tns:IdCorrectAnswer>7</tns:IdCorrectAnswer>
    <tns:CorrectAnswer>tns:set,map,list</tns:CorrectAnswer>
    <tns:LOGIN>tns:user</tns:LOGIN>
    <tns:PASSWORD>tns:user</tns:PASSWORD>
    <tns:ROLE>tns:student</tns:ROLE>
    <tns:TESTANSWER>0</tns:TESTANSWER>
  </tns:test>
</tns:tests>
